mutation CreatePost($postInput: CreatePostInput!) {
  createPost(PostInput: $postInput) {
    author {
      _id
      name
      avatarImage
    }
    body
    likes
    _id
    categories
  }
}

mutation DeletePost($deletePostId: String!) {
  deletePost(id: $deletePostId) 
}

mutation CreateUser($userInput: CreateUserInput!) {
  createUser(UserInput: $userInput) {
    username
    email
  }
}

mutation DeleteUser($deleteUserId: String!) {
  deleteUser(id: $deleteUserId)
}

mutation ProviderAuthUser($userInput: AuthUserInput!) {
  providerAuthUser(UserInput: $userInput)
}