mutation CreatePost($postInput: CreatePostInput!) {
  createPost(PostInput: $postInput) {
    author {
      _id
      name
      avatarImage
    }
    body
    likesCount
    _id
    categories
  }
}

mutation DeletePost($deletePostId: String!) {
  deletePost(id: $deletePostId) 
}

mutation CreateUser($userInput: CreateUserInput!) {
  createUser(UserInput: $userInput) {
    username
    email
  }
}

mutation DeleteUser($deleteUserId: String!) {
  deleteUser(id: $deleteUserId)
}

mutation ProviderAuthUser($userInput: AuthUserInput!) {
  providerAuthUser(UserInput: $userInput)
}

mutation LikePost($userId: String!, $postId: String!) {
  likePost(userId: $userId, id: $postId) {
    likedByUsers
    likesCount
  }
}

mutation UnlikePost($userId: String!, $postId: String!) {
  unlikePost(userId: $userId, id: $postId) {
    likesCount
    likedByUsers
  }
}

mutation CreateComment($commentInput: CreateCommentInput!, $populate: Boolean) {
  createComment(CommentInput: $commentInput, populate: $populate) {
    _id
    body
    author {
      _id
      name
      avatarImage
    }
  }
}

mutation DeleteComment($deleteCommentId: String!) {
  deleteComment(id: $deleteCommentId)
}

mutation FollowUser($userId: String!, $followerId: String!) {
  followUser(userId: $userId, followerId: $followerId)
}

mutation UnfollowUser($userId: String!, $followerId: String!) {
  unfollowUser(userId: $userId, followerId: $followerId)
}