query Posts($limit: Float!) {
  posts(limit: $limit) {
    _id
    body
    likesCount
    likedByUsers
    comments
    author {
      _id
      avatarImage
      name
    }
  }
}

query PostsAll {
  posts {
    _id
    categories
    body
    likesCount
    author {
      _id
      avatarImage
      name
    }
  }
}


query User($userId: String!) {
  user(id: $userId) {
    _id
    name
    username
    avatar
    email
  }
}

query Users {
  users {
    _id
    name
    username
    email
    avatar
  }
}
