query PostByPostId($postId: String!, $populateComments: Boolean!) {
  postByPostId(postId: $postId,  populateComments: $populateComments) {
    body
    _id
    author {
      _id
      name
      avatarImage
    }
    categories
    comments {
      ... on Comment {
        _id
        body
        author {
          _id
          name
          avatarImage
        }
        likesCount
        likedByUsers
      }
      ... on CommentId {
        _id
      }
    }
    commentsCount
    likedByUsers
    likesCount
  }
}

query PostByUserId($userId: String!) {
  postByUserId(userId: $userId) {
    _id
    body
    author {
      _id
      name
      avatarImage
    }
  }
}

query Posts($limit: Float!) {
  posts(limit: $limit) {
    _id
    body
    likesCount
    likedByUsers
    commentsCount
    author {
      _id
      avatarImage
      name
    }
    comments {
      ... on CommentId {
        _id
      }
    }
  }
}

query PostsAll {
  posts {
    _id
    categories
    body
    likesCount
    author {
      _id
      avatarImage
      name
    }
  }
}


query User($userId: String!) {
  user(id: $userId) {
    _id
    name
    username
    avatar
    email
  }
}

query Users {
  users {
    _id
    name
    username
    email
    avatar
  }
}

query CommentById($commentByIdId2: String!, $commentByIdPopulate2: Boolean) {
  commentById(id: $commentByIdId2, populate: $commentByIdPopulate2) {
    _id
    author {
      _id
      name
      avatarImage
    }
    postId {
      ... on PostId {
        _id
      }
      ... on Post {
        _id
        body
        categories
        commentsCount
        likedByUsers
        likesCount
      }
    }
    body
    commentsCount
    likedByUsers
    likesCount
  }
}

query CommentsByPostId($postId: String!) {
  commentsByPostId(postId: $postId) {
    _id
    body
    author {
      _id
      name
      avatarImage
    }
  }
}

